baseURL = 'https://alank976.github.io/blog'
languageCode = 'en-us'
title = "Alan Kan's Developer Blog"
theme = "PaperMod"

# For PaperMod
paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]


[params]
env = "production"
title = "Alan Kan's Developer Blog"
description = "A blog written by yet another developer called Alan Kan "
keywords = ["Blog", "PaperMod"]
author = "Me"
# images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "2006-01-02"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "https://github.githubassets.com/favicons/favicon-dark.svg"
# favicon16x16 = "<link / abs url>"
# favicon32x32 = "<link / abs url>"
# apple_touch_icon = "<link / abs url>"
# safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
# icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false

# [[params.profileMode.buttons]]
# name = "Posts"
# url = "posts"

# [[params.profileMode.buttons]]
# name = "Tags"
# url = "tags"

[params.homeInfoParams]
Title = "Welcome to Alan Kan's developer blog ğŸ‘‹"
Content = """
This blog is a place to log my learning experiences, and maybe some reflections I have along my full time job or my toy projectsğŸ¤–

Though I probably just talk to myself here in most of the cases, do feel free to leave your comments anytime. Feedback is always welcomedğŸ˜‰
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/alank976"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/alankan976/"

# [params.analytics.google]
# SiteVerificationTag = "XYZabc"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/alank976/blog/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

# Add menu to site
# https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#add-menu-to-site
[languages.en]
languageName = "English"
weight = 1

[languages.zh_hk]
languageAltTitle = "ç¹é«”ä¸­æ–‡(é¦™æ¸¯)"

weight = 2
title = "Alan Kançš„Developer Blog"
[languages.zh_hk.homeInfoParams]
Title = "æ­¡è¿ä¾†åˆ°Alan Kançš„Developer BlogğŸ‘‹"
Content = """
é€™å€‹Blogæ˜¯ç”¨ä¾†ç´€éŒ„æˆ‘åœ¨æˆ‘çš„å…¨è·å·¥ä½œæˆ–ç§ä¸‹çš„toy projectğŸ¤–æ™‚çš„å­¸ç¿’å¿ƒå¾—åŠé«”æœƒ. 

é›–ç„¶å¾ˆå¤§æ©Ÿæœƒæˆ‘åªæœƒåœ¨é€™è£¡è‡ªè¨€å…ˆèª, ä¸éæˆ‘éå¸¸æ­¡è¿ç•™è¨€ğŸ˜‰
"""

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About me"
url = "https://alank976.github.io/markdown-resume/"
weight = 20
